"""add host protocol_version

Revision ID: 038acf539985
Revises: d6bcb4da5c4b
Create Date: 2026-09-21 22:49:21.320765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038acf539985'
down_revision: Union[str, None] = 'd6bcb4da5c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('protocol_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'protocol_version')
    # ### end Alembic commands ###
