"""initial schema

Revision ID: 6277151d1f2d
Revises: 
Create Date: 2026-09-17 12:13:40.827340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6277151d1f2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by_host_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_tokens_token_hash'), 'enrollment_tokens', ['token_hash'], unique=True)
    op.create_table('hosts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('operating_system', sa.String(length=32), nullable=False),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('architecture', sa.String(length=64), nullable=True),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('docker_available', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_scan_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hosts_hostname', 'hosts', ['hostname'], unique=False)
    op.create_table('agent_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_credentials_host_id'), 'agent_credentials', ['host_id'], unique=False)
    op.create_index(op.f('ix_agent_credentials_token_hash'), 'agent_credentials', ['token_hash'], unique=True)
    op.create_table('central_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.Enum('tcp', 'udp', name='protocol'), nullable=False),
    sa.Column('bind_address', sa.String(length=64), nullable=True),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('local_reservation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'port', 'protocol', 'bind_address', name='uq_central_reservation_binding')
    )
    op.create_index(op.f('ix_central_reservations_host_id'), 'central_reservations', ['host_id'], unique=False)
    op.create_index(op.f('ix_central_reservations_local_reservation_id'), 'central_reservations', ['local_reservation_id'], unique=False)
    op.create_table('current_port_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.Enum('tcp', 'udp', name='protocol'), nullable=False),
    sa.Column('bind_address', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'FREE', 'RESERVED', 'CONFLICT', 'SYSTEM', name='port_state'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(length=512), nullable=True),
    sa.Column('process_path', sa.String(length=1024), nullable=True),
    sa.Column('working_directory', sa.String(length=1024), nullable=True),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('container_name', sa.String(length=255), nullable=True),
    sa.Column('container_image', sa.String(length=512), nullable=True),
    sa.Column('container_port', sa.Integer(), nullable=True),
    sa.Column('docker_compose_project', sa.String(length=255), nullable=True),
    sa.Column('service_name', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('detection_confidence', sa.String(length=16), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'port', 'protocol', 'bind_address', name='uq_current_port_binding')
    )
    op.create_index(op.f('ix_current_port_observations_host_id'), 'current_port_observations', ['host_id'], unique=False)
    op.create_index('ix_current_port_observations_port', 'current_port_observations', ['port'], unique=False)
    op.create_index('ix_current_port_observations_project', 'current_port_observations', ['project_name'], unique=False)
    op.create_table('port_observation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.Enum('tcp', 'udp', name='protocol'), nullable=False),
    sa.Column('bind_address', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'FREE', 'RESERVED', 'CONFLICT', 'SYSTEM', name='port_state'), nullable=True),
    sa.Column('process_name', sa.String(length=512), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_port_observation_events_host_id'), 'port_observation_events', ['host_id'], unique=False)
    op.create_index('ix_port_observation_events_host_port', 'port_observation_events', ['host_id', 'port', 'protocol'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_host_id'), 'scans', ['host_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_host_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index('ix_port_observation_events_host_port', table_name='port_observation_events')
    op.drop_index(op.f('ix_port_observation_events_host_id'), table_name='port_observation_events')
    op.drop_table('port_observation_events')
    op.drop_index('ix_current_port_observations_project', table_name='current_port_observations')
    op.drop_index('ix_current_port_observations_port', table_name='current_port_observations')
    op.drop_index(op.f('ix_current_port_observations_host_id'), table_name='current_port_observations')
    op.drop_table('current_port_observations')
    op.drop_index(op.f('ix_central_reservations_local_reservation_id'), table_name='central_reservations')
    op.drop_index(op.f('ix_central_reservations_host_id'), table_name='central_reservations')
    op.drop_table('central_reservations')
    op.drop_index(op.f('ix_agent_credentials_token_hash'), table_name='agent_credentials')
    op.drop_index(op.f('ix_agent_credentials_host_id'), table_name='agent_credentials')
    op.drop_table('agent_credentials')
    op.drop_index('ix_hosts_hostname', table_name='hosts')
    op.drop_table('hosts')
    op.drop_index(op.f('ix_enrollment_tokens_token_hash'), table_name='enrollment_tokens')
    op.drop_table('enrollment_tokens')
    # ### end Alembic commands ###
