"""add host probes

Revision ID: d6bcb4da5c4b
Revises: e53bf191ea97
Create Date: 2026-09-21 16:41:34.457892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd6bcb4da5c4b'
down_revision: Union[str, None] = 'e53bf191ea97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # The `protocol` ENUM TYPE already exists (created by the initial
    # schema migration for central_reservations/current_port_observations/
    # port_observation_events) -- create_type=False reuses it instead of
    # trying to CREATE TYPE a second time, which Postgres rejects outright
    # (DuplicateObject). This is a real bug autogenerate doesn't catch on
    # its own, caught by actually running `alembic upgrade head` against
    # the real dev database rather than trusting the generated file as-is.
    op.create_table('host_probes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', postgresql.ENUM('tcp', 'udp', name='protocol', create_type=False), nullable=False),
    sa.Column('bind_address', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_available', sa.Boolean(), nullable=True),
    sa.Column('result_reason', sa.String(length=512), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_probes_expires_at'), 'host_probes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_host_probes_host_id'), 'host_probes', ['host_id'], unique=False)
    op.create_index(op.f('ix_host_probes_status'), 'host_probes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_probes_status'), table_name='host_probes')
    op.drop_index(op.f('ix_host_probes_host_id'), table_name='host_probes')
    op.drop_index(op.f('ix_host_probes_expires_at'), table_name='host_probes')
    op.drop_table('host_probes')
    # ### end Alembic commands ###
