"""add allocations

Revision ID: e53bf191ea97
Revises: 757214bd00e6
Create Date: 2026-09-21 10:01:11.024498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53bf191ea97'
down_revision: Union[str, None] = '757214bd00e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('request_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_host_id'), 'allocations', ['host_id'], unique=False)
    op.create_index(op.f('ix_allocations_request_id'), 'allocations', ['request_id'], unique=True)
    op.add_column('central_reservations', sa.Column('allocation_id', sa.UUID(), nullable=True))
    op.add_column('central_reservations', sa.Column('request_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_central_reservations_allocation_id'), 'central_reservations', ['allocation_id'], unique=False)
    op.create_foreign_key(
        'fk_central_reservations_allocation_id', 'central_reservations', 'allocations',
        ['allocation_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_central_reservations_allocation_id', 'central_reservations', type_='foreignkey')
    op.drop_index(op.f('ix_central_reservations_allocation_id'), table_name='central_reservations')
    op.drop_column('central_reservations', 'request_name')
    op.drop_column('central_reservations', 'allocation_id')
    op.drop_index(op.f('ix_allocations_request_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_host_id'), table_name='allocations')
    op.drop_table('allocations')
    # ### end Alembic commands ###
